export const REQUEST_ALL_PIECE_DATA = 'REQUEST_ALL_PIECE_DATA';

export const RECEIVE_ALL_PIECE_DATA = 'RECEIVE_ALL_PIECE_DATA';

export const SUBMIT_NEW_PIECE_DATA = 'SUBMIT_NEW_PIECE_DATA';

export const REQUEST_ADD_PIECE = 'REQUEST_ADD_PIECE';

export const RECEIVE_ADD_PIECE = 'RECEIVE_ADD_PIECE';
